### PR TITLE
Simplify channel title

### PR DESCRIPTION
**Pull request by Nicell**
Remove estimated because on most discord clients it cuts off the "in-upl" part. We can explain the estimation in the channel with the bot

### CODE REVIEW

**Comment by glassglue** [comment]
Introduction:
This update addresses the previous implementation's issue of truncated channel names in most Discord clients, resulting in a loss of information. By removing the "estimated" portion of the channel name and providing a more concise representation, we ensure that the channel name remains informative and visible to users.

Problem:
The original code utilized the word "estimated" in the channel name to represent an approximation of the number of people in an "upload" state. However, the inclusion of "estimated" led to the truncation of the "in-upl" part of the channel name in most Discord clients. As a result, users were unable to see the complete information.

Solution:
To resolve this issue, we have removed the "estimated" portion of the channel name and updated the code to provide a more concise representation of the number of people in an "upload" state. This change ensures that the channel name remains informative and fully visible in most Discord clients. The code now follows this structure:

Explanation:
The updated code checks if there is only one person in an "upload" state and appends "person-in-upl" to the channel name, e.g., "1-person-in-upl". If there are multiple people in an "upload" state, it appends "people-in-upl" instead, e.g., "{people_count}-people-in-upl". The new channel name structure ensures that the information is clear and not truncated in most Discord clients.

Regarding the estimation explanation, it is now assumed that this information will be provided in the channel where the bot is active, rather than in the channel name itself. This approach maintains the necessary context without negatively impacting the channel name's visibility.

Conclusion:
The updated code provides a more efficient and user-friendly solution for representing the number of people in an "upload" state within a Discord channel's name. By removing the "estimated" portion and utilizing a more concise representation, we ensure that users can view the complete channel name in most Discord clients. The estimation explanation will now be provided within the channel where the bot is active, maintaining the necessary context without impacting visibility.

**Comment by glassglue** [comment]
lgtm

**Comment by mdberkey** [comment]
Excellent commit and write up, but be a little more verbose next time please.

**Review by mdberkey — COMMENTED** [review]
lgtm

**Pull request merged**
